name: Publish UI Package

on:
  push:
    branches:
      - main
    paths:
      - 'packages/ui/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: npx turbo run build --scope=@zoe/ui

      - name: Publish package
        run: |
          cd packages/ui
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
